# Generated by Django 5.1.2 on 2024-10-10 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': '3. Продукт',
                'verbose_name_plural': '3. Продукты',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diameter', models.FloatField(blank=True, default=0, null=True, verbose_name='Диаметры')),
                ('size', models.FloatField(blank=True, default=0, null=True, verbose_name='Размер, DxT')),
                ('weight', models.FloatField(blank=True, default=0, null=True, verbose_name='Масса, кг')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Дата публикации')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Дата публикации')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='blog.category', verbose_name='Родитель категории')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
            ],
            options={
                'verbose_name': '2. Подкатегория',
                'verbose_name_plural': '2. Подкатегория',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('blog.category',),
        ),
        migrations.CreateModel(
            name='TopLevelCategory',
            fields=[
            ],
            options={
                'verbose_name': '1. Основная категория',
                'verbose_name_plural': '1. Основная категория',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('blog.category',),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/product', verbose_name='Продукт картинки')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productImage', to='blog.product', verbose_name='Продукт')),
            ],
        ),
    ]
