# Generated by Django 5.1.2 on 2024-10-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_product_category_productdetail_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Название категория'),
        ),
    ]
