# Generated by Django 5.1.2 on 2024-10-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_product_description_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='size',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Размер, DxT'),
        ),
    ]
