# Generated by Django 5.1.2 on 2024-10-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_contacts_alter_productdetail_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'ordering': ['id'], 'verbose_name': '4. Обратной связи', 'verbose_name_plural': '4. Обратной связи'},
        ),
        migrations.AddField(
            model_name='contacts',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата публикации'),
        ),
    ]
