# Generated by Django 5.1.2 on 2024-10-11 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_contacts_options_contacts_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='file1',
            field=models.FileField(blank=True, null=True, upload_to='file1/', verbose_name='Прикрепить заявку'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to='file1/', verbose_name='Прикрепить реквизиты'),
        ),
    ]
