# Generated by Django 5.1.2 on 2024-10-11 07:04

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_contacts_file1_contacts_file2'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(default=1, verbose_name='Краткое описание'),
            preserve_default=False,
        ),
    ]
