# Generated by Django 5.1.2 on 2024-10-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='email',
            field=models.EmailField(blank=True, max_length=250, null=True, verbose_name='Адрес электронной почты'),
        ),
    ]
